
/**
 *
 * @author Isiah John
 */
public class LoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());

    private Login login;
    private MemberManager memberManager;
    private StaffManager staffManager;
    private MembershipManager membershipManager;
    private CreditCardManager cardManager;
    private Facility facility;
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI()
    {
        initComponents();
        memberManager = new MemberManager();
        staffManager = new StaffManager();
        membershipManager = new MembershipManager();
        cardManager = new CreditCardManager();
        facility = new Facility();
        login = new Login(memberManager, staffManager);
        membershipManager.loadMembership("memberships.txt");
        memberManager.loadMembersFromFile("members.txt",membershipManager);
        staffManager.loadStaffFromFile("staff.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMemberLogin = new javax.swing.JButton();
        btnStaffLogin = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(300, 270));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMemberLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMemberLogin.setText("Member Login");
        btnMemberLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnMemberLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, -1));

        btnStaffLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStaffLogin.setText("Staff Login");
        btnStaffLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnStaffLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, -1));

        btnQuit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(312, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMemberLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberLoginActionPerformed

        new MemberLoginGUI(login, memberManager, membershipManager, cardManager, facility).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMemberLoginActionPerformed

    private void btnStaffLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLoginActionPerformed
        new StaffLoginGUI(login, staffManager, memberManager, membershipManager, cardManager, facility).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStaffLoginActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMemberLogin;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnStaffLogin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
