
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author falco
 */
public class MemberLoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MemberLoginGUI.class.getName());
    private Login loginObject;
    private MemberManager memberManager;
    private MembershipManager membershipManager;
    private CreditCardManager cardManager;
    private Facility facility;
    
    /**
     * Creates new form MemberLoginFormGUI
     */
    public MemberLoginGUI() {
        initComponents();
    }
    
    public MemberLoginGUI(Login login, MemberManager mm, MembershipManager ms, CreditCardManager cc, Facility facility)
    {
        this();
        this.loginObject = login;
        this.memberManager = mm;
        this.membershipManager = ms;
        this.cardManager = cc;
        this.facility = facility;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMUsername = new javax.swing.JLabel();
        lblMPassword = new javax.swing.JLabel();
        txtMUsername = new javax.swing.JTextField();
        btnMLogin = new javax.swing.JButton();
        btnMSignup = new javax.swing.JButton();
        lblMTitle = new javax.swing.JLabel();
        pfMPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Member Login");
        setPreferredSize(new java.awt.Dimension(300, 270));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMUsername.setText("Username:");
        getContentPane().add(lblMUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblMPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMPassword.setText("Password:");
        getContentPane().add(lblMPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtMUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtMUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 200, -1));

        btnMLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMLogin.setText("Sign In");
        btnMLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnMLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, -1));

        btnMSignup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMSignup.setText("Sign Up");
        btnMSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnMSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        lblMTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMTitle.setText("Member Login");
        getContentPane().add(lblMTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        pfMPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pfMPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, -1));

        setSize(new java.awt.Dimension(312, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMUsernameActionPerformed

    private void btnMLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMLoginActionPerformed
        
        String MemberUsername = txtMUsername.getText();
        String MemberPassword = String.valueOf(pfMPassword.getPassword());
        
        if(MemberUsername.isEmpty() || MemberPassword.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill in both username and password",
                    "Missin Information", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Member member = loginObject.loginMember(MemberUsername, MemberPassword);
        
        if(member != null)
        {
            new MemberMenuGUI(member, memberManager, membershipManager, cardManager, facility).setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Incorrect username or password", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnMLoginActionPerformed

    private void btnMSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSignupActionPerformed
        
    }//GEN-LAST:event_btnMSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MemberLoginGUI().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMLogin;
    private javax.swing.JButton btnMSignup;
    private javax.swing.JLabel lblMPassword;
    private javax.swing.JLabel lblMTitle;
    private javax.swing.JLabel lblMUsername;
    private javax.swing.JPasswordField pfMPassword;
    private javax.swing.JTextField txtMUsername;
    // End of variables declaration//GEN-END:variables
}
