
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author falco
 */
public class StaffLoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffLoginGUI.class.getName());

    private Login loginObject;
    private StaffManager staffManager;
    private MemberManager memberManager;
    private MembershipManager membershipManager;
    private Facility facility;
    
    /**
     * Creates new form StaffLoginGUI
     */
    public StaffLoginGUI() {
        initComponents();
    }
    
    public StaffLoginGUI(Login login, StaffManager sm, MemberManager mm, MembershipManager ms, Facility facility)
    {
        this();
        this.loginObject = login;
        this.memberManager = mm;
        this.membershipManager = ms;
        this.staffManager = sm;
        this.facility = facility;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSUsername = new javax.swing.JLabel();
        txtSUsername = new javax.swing.JTextField();
        lblSPassword = new javax.swing.JLabel();
        btnSLogin = new javax.swing.JButton();
        lblSTitle = new javax.swing.JLabel();
        lblSTitle2 = new javax.swing.JLabel();
        pfSPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSUsername.setText("Username:");
        getContentPane().add(lblSUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtSUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtSUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 200, -1));

        lblSPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSPassword.setText("Password:");
        getContentPane().add(lblSPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        btnSLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSLogin.setText("Sign in");
        btnSLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnSLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, -1));

        lblSTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSTitle.setText("Staff Login");
        getContentPane().add(lblSTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        lblSTitle2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSTitle2.setText("Management System");
        getContentPane().add(lblSTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        pfSPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pfSPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, -1));

        setSize(new java.awt.Dimension(312, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSLoginActionPerformed
        String StaffUsername = txtSUsername.getText();
        String StaffPassword = String.valueOf(pfSPassword.getPassword());
        
        if(StaffUsername.isEmpty() || StaffPassword.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill in both username and password",
                    "Missin Information", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Staff staff = loginObject.loginStaff(StaffUsername, StaffPassword);
        
        if(staff != null)
        {
            new StaffMenuGUI(staff, memberManager, membershipManager, staffManager, facility).setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No Account Found with Username or Password");
        }
    }//GEN-LAST:event_btnSLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffLoginGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSLogin;
    private javax.swing.JLabel lblSPassword;
    private javax.swing.JLabel lblSTitle;
    private javax.swing.JLabel lblSTitle2;
    private javax.swing.JLabel lblSUsername;
    private javax.swing.JPasswordField pfSPassword;
    private javax.swing.JTextField txtSUsername;
    // End of variables declaration//GEN-END:variables
}
