import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Isiah John
 */
public class StaffMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffMenuGUI.class.getName());
    //private Login loginObject;
    private Staff staff;
    private StaffManager staffManager;
    private MemberManager memberManager;
    private MembershipManager membershipManager;
    private CreditCardManager cardManager;
    private Facility facility;
    

    /**
     * Creates new form StaffMenuGUI
     */
    public StaffMenuGUI() {
        initComponents();
    }
    
    public StaffMenuGUI(Staff st, MemberManager mm, MembershipManager ms, StaffManager sm, CreditCardManager ccManager, Facility facility)
    {
        this();
        //this.loginObject = login;
        this.staff = st;
        this.staffManager = sm;
        this.memberManager = mm;
        this.membershipManager = ms;
        this.cardManager = ccManager;
        this.facility = facility;
        
        lblWelcome.setText("Welcome " + staff.getName() + " to the Management System");
        initMembershipComboBox();
        initFacilityInventoryComboBox();
    }
    
    public void initMembershipComboBox()
    {
        //cbMembership.removeAllItems();
        cbMembership.addItem("None");
        for(Membership m : membershipManager.getMemberships())
        {
            cbMembership.addItem(m.getType());
        }
    }
    
    public void initFacilityInventoryComboBox()
    {
        //cbFacilityAreaInvent.removeAllItems();
        cbFacilityAreaInvent.addItem("None");
        for(Area a : facility.getAreas())
        {
            if(a.hasInventory())
            {
                cbFacilityAreaInvent.addItem(a.getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGFacilityInventory = new javax.swing.ButtonGroup();
        btnGFacilityClasses = new javax.swing.ButtonGroup();
        pManageFacility = new javax.swing.JTabbedPane();
        pDashboard = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pManageMembers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblMName = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        lblMUsername = new javax.swing.JLabel();
        txtMUsername = new javax.swing.JTextField();
        lblMPassword = new javax.swing.JLabel();
        txtMPassword = new javax.swing.JTextField();
        lblMMembership = new javax.swing.JLabel();
        cbMembership = new javax.swing.JComboBox<>();
        btnMAdd = new javax.swing.JButton();
        btnMEdit = new javax.swing.JButton();
        btnMRemove = new javax.swing.JButton();
        pManageMembership = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMembershipType = new javax.swing.JLabel();
        txtMemType = new javax.swing.JTextField();
        lblMembershipCost = new javax.swing.JLabel();
        txtMemCost = new javax.swing.JTextField();
        btnMemRemove = new javax.swing.JButton();
        btnMemAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMemberships = new javax.swing.JTable();
        pManageClasses = new javax.swing.JPanel();
        pManageStaff = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblSName = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        lblSUsername = new javax.swing.JLabel();
        txtSUsername = new javax.swing.JTextField();
        lblSPassword = new javax.swing.JLabel();
        txtSPassword = new javax.swing.JTextField();
        btnSEdit = new javax.swing.JButton();
        btnSRemove = new javax.swing.JButton();
        btnSAdd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        pManageInventory = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbFacilityAreaInvent = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblFName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        rbtnYesi = new javax.swing.JRadioButton();
        rbtnNoi = new javax.swing.JRadioButton();
        lblFInventory = new javax.swing.JLabel();
        btnFEdit = new javax.swing.JButton();
        btnFAdd = new javax.swing.JButton();
        btnFRemove = new javax.swing.JButton();
        lblFClasses = new javax.swing.JLabel();
        rbtnFYesc = new javax.swing.JRadioButton();
        rbtnFNoc = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFacility = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff Management Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pManageFacility.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pManageFacilityStateChanged(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btnLogout)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pManageFacility.addTab("Dashboard", pDashboard);

        tblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Password", "Membership"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMembersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMembers);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Member Info"));

        lblMName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMName.setText("Name");

        txtMName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMUsername.setText("Username");

        txtMUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMPassword.setText("Password");

        txtMPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMMembership.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMMembership.setText("Membership");

        btnMAdd.setText("Add Member");
        btnMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAddActionPerformed(evt);
            }
        });

        btnMEdit.setText("Update");
        btnMEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEditActionPerformed(evt);
            }
        });

        btnMRemove.setText("Remove");
        btnMRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMPassword)
                    .addComponent(txtMUsername)
                    .addComponent(txtMName)
                    .addComponent(cbMembership, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMName)
                            .addComponent(lblMUsername)
                            .addComponent(lblMPassword)
                            .addComponent(lblMMembership))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addComponent(btnMAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblMName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMMembership)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMembership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMEdit)
                    .addComponent(btnMRemove))
                .addGap(28, 28, 28)
                .addComponent(btnMAdd)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pManageMembersLayout = new javax.swing.GroupLayout(pManageMembers);
        pManageMembers.setLayout(pManageMembersLayout);
        pManageMembersLayout.setHorizontalGroup(
            pManageMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pManageMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        pManageMembersLayout.setVerticalGroup(
            pManageMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pManageMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManageMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pManageFacility.addTab("Members", pManageMembers);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Membership Info"));
        jPanel2.setPreferredSize(new java.awt.Dimension(216, 383));

        lblMembershipType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMembershipType.setText("Type");

        txtMemType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMembershipCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMembershipCost.setText("Cost");

        txtMemCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnMemRemove.setText("Remove");
        btnMemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemRemoveActionPerformed(evt);
            }
        });

        btnMemAdd.setText("Add");
        btnMemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMemCost)
                    .addComponent(txtMemType)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMembershipType)
                            .addComponent(lblMembershipCost))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnMemAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMemRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMembershipType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMembershipCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnMemRemove)
                .addGap(18, 18, 18)
                .addComponent(btnMemAdd)
                .addGap(106, 106, 106))
        );

        tblMemberships.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMemberships);

        javax.swing.GroupLayout pManageMembershipLayout = new javax.swing.GroupLayout(pManageMembership);
        pManageMembership.setLayout(pManageMembershipLayout);
        pManageMembershipLayout.setHorizontalGroup(
            pManageMembershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManageMembershipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pManageMembershipLayout.setVerticalGroup(
            pManageMembershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManageMembershipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManageMembershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pManageFacility.addTab("Membership", pManageMembership);

        javax.swing.GroupLayout pManageClassesLayout = new javax.swing.GroupLayout(pManageClasses);
        pManageClasses.setLayout(pManageClassesLayout);
        pManageClassesLayout.setHorizontalGroup(
            pManageClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        pManageClassesLayout.setVerticalGroup(
            pManageClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        pManageFacility.addTab("Classes", pManageClasses);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Staff Info"));

        lblSName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSName.setText("Name");

        txtSName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSUsername.setText("Username");

        txtSUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSPassword.setText("Password");

        txtSPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSEdit.setText("Update");
        btnSEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEditActionPerformed(evt);
            }
        });

        btnSRemove.setText("Remove");
        btnSRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSRemoveActionPerformed(evt);
            }
        });

        btnSAdd.setText("Add Staff");
        btnSAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSName)
                    .addComponent(txtSUsername)
                    .addComponent(txtSPassword)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSName)
                            .addComponent(lblSUsername)
                            .addComponent(lblSPassword))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSEdit)
                    .addComponent(btnSRemove))
                .addGap(18, 18, 18)
                .addComponent(btnSAdd)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblStaff);

        javax.swing.GroupLayout pManageStaffLayout = new javax.swing.GroupLayout(pManageStaff);
        pManageStaff.setLayout(pManageStaffLayout);
        pManageStaffLayout.setHorizontalGroup(
            pManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManageStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pManageStaffLayout.setVerticalGroup(
            pManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManageStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pManageFacility.addTab("Staff", pManageStaff);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Inventory"));

        jLabel1.setText("Facility Areas w/ Inventory");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFacilityAreaInvent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(cbFacilityAreaInvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout pManageInventoryLayout = new javax.swing.GroupLayout(pManageInventory);
        pManageInventory.setLayout(pManageInventoryLayout);
        pManageInventoryLayout.setHorizontalGroup(
            pManageInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManageInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pManageInventoryLayout.setVerticalGroup(
            pManageInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManageInventoryLayout.createSequentialGroup()
                .addGroup(pManageInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pManageInventoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pManageFacility.addTab("Inventory", pManageInventory);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Facility Areas"));

        lblFName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFName.setText("Name");

        txtFName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGFacilityInventory.add(rbtnYesi);
        rbtnYesi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnYesi.setText("Yes");

        btnGFacilityInventory.add(rbtnNoi);
        rbtnNoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnNoi.setSelected(true);
        rbtnNoi.setText("No");

        lblFInventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFInventory.setText("Will This Have an Inventory?");

        btnFEdit.setText("Update");
        btnFEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFEditActionPerformed(evt);
            }
        });

        btnFAdd.setText("Add Facility Area");
        btnFAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAddActionPerformed(evt);
            }
        });

        btnFRemove.setText("Remove");
        btnFRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFRemoveActionPerformed(evt);
            }
        });

        lblFClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFClasses.setText("Will this host Class session?");

        btnGFacilityClasses.add(rbtnFYesc);
        rbtnFYesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnFYesc.setText("Yes");

        btnGFacilityClasses.add(rbtnFNoc);
        rbtnFNoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnFNoc.setSelected(true);
        rbtnFNoc.setText("No");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFName)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblFName)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(rbtnYesi)
                            .addGap(18, 18, 18)
                            .addComponent(rbtnNoi))
                        .addComponent(lblFInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbtnFYesc)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnFNoc)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblFName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnYesi)
                    .addComponent(rbtnNoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFClasses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFYesc)
                    .addComponent(rbtnFNoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFEdit)
                    .addComponent(btnFRemove))
                .addGap(18, 18, 18)
                .addComponent(btnFAdd)
                .addGap(14, 14, 14))
        );

        tblFacility.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Area Name", "Inventory?", "Classes?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFacility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacilityMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblFacility);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pManageFacility.addTab("Facility", jPanel5);

        getContentPane().add(pManageFacility, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        setSize(new java.awt.Dimension(654, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new LoginGUI().setVisible(true);
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        loadMemberTable();
        loadMembershipTable();
        loadStaffTable();
        loadFacilityTable();
    }//GEN-LAST:event_formWindowOpened

    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAddActionPerformed
        try
        {
            
            String[] tableRow = {txtMName.getText(),txtMUsername.getText(),txtMPassword.getText(),cbMembership.getSelectedItem().toString()};
            DefaultTableModel model = (DefaultTableModel) tblMembers.getModel();
            model.addRow(tableRow);
            clearFields();
            
            ArrayList<String> tableData = getTableData(model);
            if(memberManager.saveMemberFile("members.txt", tableData))
            {
                JOptionPane.showMessageDialog(this,"Saved to Member File");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Failed to Add Member");
        }
    }//GEN-LAST:event_btnMAddActionPerformed

    private void btnMRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRemoveActionPerformed
        int row = tblMembers.getSelectedRow();
        if(row < 0)
        {
            JOptionPane.showMessageDialog(this,"You need to select a row.");
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblMembers.getModel();
            int result = JOptionPane.showConfirmDialog(null, "Do you want to remove this member from file?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION)
            {
                model.removeRow(row);
                
                ArrayList<String> tableData = getTableData(model);
                memberManager.saveMemberFile("members.txt",tableData);
                JOptionPane.showMessageDialog(this,"Member Delected Successfully from File");
            }
            else if(result == JOptionPane.NO_OPTION)
            {
                return;
            }
        }
    }//GEN-LAST:event_btnMRemoveActionPerformed

    private void tblMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMembersMouseClicked
        int row = tblMembers.getSelectedRow();
        if(row<0)
        {
            return;
        }
        String name = tblMembers.getValueAt(row,0).toString();
        String username = tblMembers.getValueAt(row,1).toString();
        String password = tblMembers.getValueAt(row,2).toString();
        String memberships = tblMembers.getValueAt(row,3).toString();
        Member selectedMember = memberManager.findMemberByUsername(username);
        
        if(selectedMember == null)
        {
            return;
        }
        
        txtMName.setText(selectedMember.getName());
        txtMUsername.setText(selectedMember.getUsername());
        txtMPassword.setText(selectedMember.getPassword());
        cbMembership.setSelectedItem(memberships);
        
    }//GEN-LAST:event_tblMembersMouseClicked

    private void btnMEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEditActionPerformed
        int row = tblMembers.getSelectedRow();
        if(row<0)
        {
            JOptionPane.showMessageDialog(this,"Please Select a Member to Update info");
            return;
        }
        
        String newName = txtMName.getText().trim();
        String newUsername = txtMUsername.getText().trim();
        String newPassword = txtMPassword.getText().trim();
        String membershipType = cbMembership.getSelectedItem().toString();
        
        String originalUsername = tblMembers.getValueAt(row,1).toString();
        Member member = memberManager.findMemberByUsername(originalUsername);
        
        if(member == null)
        {
            JOptionPane.showMessageDialog(this, "Member not found");
            return;
        }
        
        member.setName(newName);
        member.setUsername(newUsername);
        member.setPassword(newPassword);
        
        if(membershipType.equals("None"))
        {
            member.setMembership(null);
        }
        else
        {
            Membership m = membershipManager.findMembership(membershipType);
            member.setMembership(m);
        }
        
        DefaultTableModel model = (DefaultTableModel) tblMembers.getModel();
        model.setValueAt(newName,row,0);
        model.setValueAt(newUsername,row,1);
        model.setValueAt(newPassword,row,2);
        model.setValueAt(membershipType,row,3);
        
        ArrayList<String> tableData = getTableData(model);
        memberManager.saveMemberFile("members.txt",tableData);
        JOptionPane.showMessageDialog(this,"Member Updated Successfully");
    }//GEN-LAST:event_btnMEditActionPerformed

    private void btnMemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemRemoveActionPerformed
        int row = tblMemberships.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblMemberships.getModel();
        if(row<0)
        {
            JOptionPane.showMessageDialog(this,"You need to select a Membership to remove.");
        }
        else
        {
            String type = tblMemberships.getValueAt(row,0).toString();
            
            for(Member m : memberManager.getMembers())
            {
                if(m.getMembership() != null && m.getMembership().getType().equalsIgnoreCase(type))
                {
                    JOptionPane.showMessageDialog(this, "Cannot delete this Membership.\n" +
                            "One or more members currently have this membership!", "Delete Blocked",JOptionPane.WARNING_MESSAGE);
                    return;
                }    
            }  
            //Get Confirmation for removing
            int confirm = JOptionPane.showConfirmDialog(this,"Do you want to remove " + type + "?", "Confirm Removal", JOptionPane.YES_NO_OPTION);
            if(confirm != JOptionPane.YES_OPTION)
            {
                return;
            }
            //REmoving Membership from the membershipmanager
            if(!membershipManager.removeMembership(type))
            {
                JOptionPane.showMessageDialog(this,"Failed to Remove membership from Manager", "Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            //saves to file
            ArrayList<String> tableData = getMembershipTableData(model);
            membershipManager.saveMembershipFile("memberships.txt", tableData);
            
            //updates table
            model.setRowCount(0);
            for(Membership m : membershipManager.getMemberships())
            {
                model.addRow(new Object[]{m.getType(),m.getCost()});
            }
            //updates combobox
            cbMembership.removeAllItems();
            cbMembership.addItem("None");
            for(Membership m : membershipManager.getMemberships())
            {
                cbMembership.addItem(m.getType());
            }
        }    
    }//GEN-LAST:event_btnMemRemoveActionPerformed

    private void btnMemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemAddActionPerformed
        try
        {
            String[] tableRow = {txtMemType.getText(),txtMemCost.getText()};
            DefaultTableModel model = (DefaultTableModel) tblMemberships.getModel();
            model.addRow(tableRow);
            
            ArrayList<String> tableData = getMembershipTableData(model);
            
            if(membershipManager.saveMembershipFile("memberships.txt", tableData))
            {
                JOptionPane.showMessageDialog(this,"Saved to Membership File");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Failed to Add Membership");
        }
    }//GEN-LAST:event_btnMemAddActionPerformed

    private void btnSAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAddActionPerformed
        try
        {
            String[] tableRow = {txtSName.getText(),txtSUsername.getText(),txtSPassword.getText()};
            DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
            model.addRow(tableRow);
            ArrayList<String> tableData = getStaffTableData(model);
            if(staffManager.saveStaffFile("staff.txt", tableData))
            {
                JOptionPane.showMessageDialog(this,"Saved to Staff File");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Failed to Add Staff");
        }
    }//GEN-LAST:event_btnSAddActionPerformed

    private void btnSRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSRemoveActionPerformed

        int row = tblStaff.getSelectedRow();
        if(row<0)
        {
            JOptionPane.showMessageDialog(this,"You need to select a row");
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
            int result = JOptionPane.showConfirmDialog(null, "Do you want to remove this staff from file?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION)
            {
                model.removeRow(row);
                ArrayList<String> tableData = getTableData(model);
                staffManager.saveStaffFile("staff.txt", tableData);
                JOptionPane.showMessageDialog(this,"Staff Delected Successfully from File");
            }
            else if(result == JOptionPane.NO_OPTION)
            {
                return;
            }
        }
    }//GEN-LAST:event_btnSRemoveActionPerformed

    private void btnSEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEditActionPerformed
        int row = tblStaff.getSelectedRow();
        if(row<0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a Staff to Update info");
            return;
        }
        String newName = txtSName.getText().trim();
        String newUsername = txtSUsername.getText().trim();
        String newPassword = txtSPassword.getText().trim();
        
        String originalUsername = tblStaff.getValueAt(row,1).toString();
        Staff staff = staffManager.findStaffByUsername(originalUsername);
        
        if(staff == null)
        {
            JOptionPane.showMessageDialog(this,"Staff not Found");
            return;
        }
        staff.setName(newName);
        staff.setUsername(newUsername);
        staff.setPassword(newPassword);
        
        DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
        model.setValueAt(newName,row,0);
        model.setValueAt(newUsername,row,1);
        model.setValueAt(newPassword,row,2);
        
        ArrayList<String> tableData = getStaffTableData(model);
        staffManager.saveStaffFile("staff.txt", tableData);
        JOptionPane.showMessageDialog(this,"Staff Updated Successfully");
    }//GEN-LAST:event_btnSEditActionPerformed

    private void btnFAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAddActionPerformed
        try
        {
            String facilityName = txtFName.getText().trim();
            boolean hasInventory = rbtnYesi.isSelected();
            boolean hasClasses = rbtnFYesc.isSelected();
            
            facility.addArea(facilityName, hasInventory,hasClasses);
            loadFacilityTable();
            
            DefaultTableModel model = (DefaultTableModel) tblFacility.getModel();
            ArrayList<String> tableData = getFacilityTableData(model);
            if(facility.saveFacilityFile("facilityArea.txt", tableData))
            {
                JOptionPane.showMessageDialog(this, "Saved to Facility File");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Failed to Add Facility Area to List file");
        }    
    }//GEN-LAST:event_btnFAddActionPerformed

    private void tblFacilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacilityMouseClicked
        int row = tblFacility.getSelectedRow();
        if(row<0)
        {
            return;
        }
        String fName = tblFacility.getValueAt(row, 0).toString();
        String hasIn = tblFacility.getValueAt(row, 1).toString();
        String hasCl = tblFacility.getValueAt(row, 2).toString();
        
        Area selectedArea = facility.findArea(fName);
        if(selectedArea == null)
        {
            return;
        }
        txtFName.setText(selectedArea.getName());
        
        rbtnYesi.setSelected(selectedArea.hasInventory());
        rbtnNoi.setSelected(!selectedArea.hasInventory());
        
        rbtnFYesc.setSelected(selectedArea.hasClasses());
        rbtnFNoc.setSelected(!selectedArea.hasClasses());
    }//GEN-LAST:event_tblFacilityMouseClicked

    private void btnFEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFEditActionPerformed
        int row = tblFacility.getSelectedRow();
        if(row<0)
        {
            JOptionPane.showMessageDialog(this, "Please Select a Facility to Update");
            return;
        }
        
        
        String oldName = tblFacility.getValueAt(row, 0).toString();
        String newName = txtFName.getText().trim();
        boolean newChoiceInv = rbtnYesi.isSelected();
        boolean newChoiceClass = rbtnFYesc.isSelected();
        
        facility.updateArea(oldName, newName, newChoiceInv, newChoiceClass);
        loadFacilityTable();
        
        DefaultTableModel model = (DefaultTableModel) tblFacility.getModel();
        ArrayList<String> tableData = getFacilityTableData(model);
        facility.saveFacilityFile("facilityArea.txt", tableData);
        JOptionPane.showMessageDialog(this,"Facility Area updated Successfully");
        
    }//GEN-LAST:event_btnFEditActionPerformed

    private void btnFRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFRemoveActionPerformed
        int row = tblFacility.getSelectedRow();
        if(row<0)
        {
            JOptionPane.showMessageDialog(this,"You need to select a row to delete");
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblFacility.getModel();
            int result = JOptionPane.showConfirmDialog(null, "Do you want to remove this Facility from File? "+
                    "\n Doing so will also delete it's Inventory File!", "Confirmation",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION)
            {
                model.removeRow(row);
                ArrayList<String> tableData = getFacilityTableData(model);
                facility.saveFacilityFile("facilityArea.txt", tableData);
                JOptionPane.showMessageDialog(this, "Facility Delected Successfully from File");
            }
            else if(result == JOptionPane.NO_OPTION)
            {
                return;
            }
        }
    }//GEN-LAST:event_btnFRemoveActionPerformed

    private void pManageFacilityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pManageFacilityStateChanged
        //initMembershipComboBox();
        //initFacilityInventoryComboBox();
    }//GEN-LAST:event_pManageFacilityStateChanged
    
    private ArrayList<String> getTableData(DefaultTableModel model)
    {
        ArrayList<String> tableData = new ArrayList<>();
            
        for(int i = 0; i< model.getRowCount(); i++)
        {
            String name = model.getValueAt(i,0).toString();
            String username = model.getValueAt(i,1).toString();
            String password = model.getValueAt(i,2).toString();
            String membershipType = model.getValueAt(i,3).toString();
                
            String row = (name + "," + username + "," + password + "," + membershipType);
            tableData.add(row);
        }
        return tableData;
    }
    
    private ArrayList<String> getStaffTableData(DefaultTableModel model)
    {
        ArrayList<String> tableData = new ArrayList<>();
        for(int i = 0; i < model.getRowCount(); i++)
        {
            String name = model.getValueAt(i,0).toString();
            String username = model.getValueAt(i,1).toString();
            String password = model.getValueAt(i,2).toString();
            String row = (name + "," + username + "," + password);
            tableData.add(row);
        }   
        return tableData;
    }
    
    private ArrayList<String> getMembershipTableData(DefaultTableModel model)
    {
        ArrayList<String> tableData = new ArrayList<>();
        for(int i = 0; i<model.getRowCount(); i++)
        {
            String type = model.getValueAt(i,0).toString();
            String cost = model.getValueAt(i, 1).toString();
            String row = (type+","+cost);
            tableData.add(row);
        }
        return tableData;
    }
    
    private ArrayList<String> getFacilityTableData(DefaultTableModel model)
    {
        ArrayList<String> tableData = new ArrayList<>();
        for(int i = 0; i < model.getRowCount(); i++)
        {
            String name = model.getValueAt(i,0).toString();
            String hasInv = model.getValueAt(i, 1).toString();
            String hasClass = model.getValueAt(i,2).toString();
            
            String row = (name+","+hasInv+","+hasClass);
            tableData.add(row);
        }
        return tableData;
    }
    
    private void clearFields()
    {
        txtMName.setText("");
        txtMUsername.setText("");
        txtMPassword.setText("");
    }
    
    private void loadMembershipTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblMemberships.getModel();
        for(Membership ms : membershipManager.getMemberships())
        {
            model.addRow(new Object[]{ms.getType(),ms.getCost()});
        }
    }
    
    private void loadMemberTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblMembers.getModel();
        for(Member m : memberManager.getMembers())
        {
            String membershipTxt = "None";
            if(m.getMembership() != null)
            {
                membershipTxt = m.getMembership().getType();
            }
            
            model.addRow(new Object[]{m.getName(),m.getUsername(), m.getPassword(),
                membershipTxt});
        }
    }
    
    private void loadStaffTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
        for(Staff s : staffManager.getStaffList())
        {
            model.addRow(new Object[]{s.getName(),s.getUsername(),s.getPassword()});
        }
    }
    
    private void loadFacilityTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblFacility.getModel();
        model.setRowCount(0);
        for(Area a : facility.getAreas())
        {
            model.addRow(new Object[]{a.getName(), a.hasInventory(),a.hasClasses()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new StaffMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFAdd;
    private javax.swing.JButton btnFEdit;
    private javax.swing.JButton btnFRemove;
    private javax.swing.ButtonGroup btnGFacilityClasses;
    private javax.swing.ButtonGroup btnGFacilityInventory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMEdit;
    private javax.swing.JButton btnMRemove;
    private javax.swing.JButton btnMemAdd;
    private javax.swing.JButton btnMemRemove;
    private javax.swing.JButton btnSAdd;
    private javax.swing.JButton btnSEdit;
    private javax.swing.JButton btnSRemove;
    private javax.swing.JComboBox<String> cbFacilityAreaInvent;
    private javax.swing.JComboBox<String> cbMembership;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFClasses;
    private javax.swing.JLabel lblFInventory;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblMMembership;
    private javax.swing.JLabel lblMName;
    private javax.swing.JLabel lblMPassword;
    private javax.swing.JLabel lblMUsername;
    private javax.swing.JLabel lblMembershipCost;
    private javax.swing.JLabel lblMembershipType;
    private javax.swing.JLabel lblSName;
    private javax.swing.JLabel lblSPassword;
    private javax.swing.JLabel lblSUsername;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel pManageClasses;
    private javax.swing.JTabbedPane pManageFacility;
    private javax.swing.JPanel pManageInventory;
    private javax.swing.JPanel pManageMembers;
    private javax.swing.JPanel pManageMembership;
    private javax.swing.JPanel pManageStaff;
    private javax.swing.JRadioButton rbtnFNoc;
    private javax.swing.JRadioButton rbtnFYesc;
    private javax.swing.JRadioButton rbtnNoi;
    private javax.swing.JRadioButton rbtnYesi;
    private javax.swing.JTable tblFacility;
    private javax.swing.JTable tblMembers;
    private javax.swing.JTable tblMemberships;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMPassword;
    private javax.swing.JTextField txtMUsername;
    private javax.swing.JTextField txtMemCost;
    private javax.swing.JTextField txtMemType;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSPassword;
    private javax.swing.JTextField txtSUsername;
    // End of variables declaration//GEN-END:variables
}
